# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/CPU/ctrlmemory.coe
add_files D:/CPU/memory.coe
read_verilog -library xil_defaultlib {
  D:/CPU/CPU.srcs/sources_1/new/alu.v
  D:/CPU/CPU.srcs/sources_1/new/counter_sync_r.v
  D:/CPU/CPU.srcs/sources_1/new/ctrlunit.v
  D:/CPU/CPU.srcs/sources_1/new/disp_dec.v
  D:/CPU/CPU.srcs/sources_1/new/dual_hex.v
  D:/CPU/CPU.srcs/sources_1/new/int_div.v
  D:/CPU/CPU.srcs/sources_1/new/register.v
  D:/CPU/CPU.srcs/sources_1/new/seg_decoder.v
  D:/CPU/CPU.srcs/sources_1/new/main.v
}
read_ip -quiet D:/CPU/CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/CPU/CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/CPU/CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]

read_ip -quiet D:/CPU/CPU.srcs/sources_1/ip/dist_mem_gen_1_2/dist_mem_gen_1.xci
set_property used_in_implementation false [get_files -all d:/CPU/CPU.srcs/sources_1/ip/dist_mem_gen_1_2/dist_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files D:/CPU/CPU.srcs/sources_1/ip/dist_mem_gen_1_2/dist_mem_gen_1.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CPU/CPU.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/CPU/CPU.srcs/constrs_1/new/constraints.xdc]


synth_design -top main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
